export const propertyDetails = [
  {
    id: 1,
    address: 'FormannstraBe12',
    postcode: 22303,
    type: 'flat',
    numberofrooms: 5,
    floorarea: 48,
  },
  {
    id: 2,
    address: 'Steinstrabe12',
    postcode: 20095,
    type: ' terracedhouse',
    numberofrooms: 7,
    floorarea: 63,
  },
  {
    id: 3,
    address: 'HimmelstrBe2',
    postcode: 22299,
    type: 'Semi-detached',
    numberofrooms: 3,
    floorarea: 22,
  },
  {
    id: 4,
    address: 'AlteSchieuse23',
    postcode: 21107,
    type: 'Terracedhouse',
    numberofrooms: 4,
    floorarea: 54,
  },
  {
    id: 5,
    address: 'Greenvalley',
    postcode: 22333,
    type: 'flat',
    numberofrooms: 6,
    floorarea: 48,
  },
  {
    id: 6,
    address: 'Himmelstreet',
    postcode: 22211,
    type: 'Semi-detached',
    numberofrooms: 2,
    floorarea: 22,
  },
];
